server:
  port: 8763
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/gn17?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: springcloudarticle
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
